name: Build and test

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Clone dependency packages
        run: |
          mkdir dependency_ws
          vcs import dependency_ws < build_depends.repos

      - name: Install missing dependencies
        run: |
          sudo apt-get update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install --ignore-src --rosdistro foxy -y \
            --from-paths obstacle_stop_planner_refine \
            --skip-keys=vehicle_info_util \
            --skip-keys=autoware_planning_msgs \
            --skip-keys=autoware_perception_msgs \
            --skip-keys=autoware_debug_msgs

      - name: Build
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build \
            --packages-up-to obstacle_stop_planner_refine \
            --event-handlers console_cohesion+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Debug

      - name: Run tests
        run: |
          . /opt/ros/foxy/setup.sh
          colcon test \
            --packages-up-to obstacle_stop_planner_refine \
            --event-handlers console_cohesion+ \
            --return-code-on-test-failure

  code-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Measure code metrics
        run: |
          git clone https://github.com/terryyin/lizard.git
          mkdir public
          git diff --name-only ${{ GITHUB_HEAD_REF }} ${{ GITHUB_BASE_REF }} | grep -E "*.hpp|*.cpp|*.py" > file_list.txt
          python3 lizard/lizard.py obstacle_stop_planner_refine/ -l cpp -l python -x"*test*" -f file_list.txt \
            --CCN 20 --length 200 --arguments 6 \
            --html > public/code-metrics.html || true
          python3 lizard/lizard.py obstacle_stop_planner_refine/ -l cpp -l python -x"*test*" -f file_list.txt \
            --CCN 20 --length 200 --arguments 6 || true

      - name: Upload measurement result page
        uses: actions/upload-artifact@v2
        with:
          name: code-metrics
          path: public

      - name: Deploy measurement result page to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

