name: Create index page
on:
  push:
    branches:
      - gh-pages

jobs:
  create-index-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Create index page
        run: |
          sudo apt-get update
          sudo apt-get install tree
          tree -H 'https://tier4.github.io/obstacle_stop_planner_refine' \
            -L 2 --noreport --charset utf-8 -T 'Index of code metrics' \
            -P "*.html" > index.html

      - name: git setting
        run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "Github Actions"

      - name: Commit file
        run: |
          git add index.html
          git commit -m "Add index.html"
          git push origin gh-pages
